#include <iostream>
#include <vector>
#include <random>
#include <fstream>
#include <algorithm>       // added for functions 1) shuffle 2) count
#include <numeric>         // added for function accumulate
#include <cmath>

// Constant parameters for simulator
const unsigned SLOTS = 30000 ;
const unsigned M = 100 ;            // bands and PUs
const unsigned N = 10 ;             // SUs
const unsigned DEMAND = 5 ;
const double Pmd = 0.1 ;
const double Pfa = 0.1 ;
const unsigned TINACTIVE = 100 ;

std::mt19937_64 randEngine{123};  // Keep the seed constant for debug for now

class Band {
public:
    bool puActive ;
    double probOFFtoON ;    // Fixed
    double probONtoOFF ;    // Variable
    unsigned int Tactive ;
    unsigned int offset ;       // Phase shift added to overcome PU synchronization
    std::vector<unsigned int> occupants;  // SUs using this band, one per band (100 total)

    // Markov chain constructor
    Band(double activityProbability):
        puActive(0),                  // Start assumption: PU is off
        probOFFtoON(1.0/TINACTIVE),   // constant and = .01
        Tactive(0),                   // offset and Tactive are zero (not used in markov)
        offset(0) {
        probONtoOFF = (1-activityProbability)/(activityProbability*TINACTIVE);
        occupants.clear();     // clear old occupancy data before processing a new time slot
    }

    // Deterministic constructor
    Band(unsigned Tactive_, unsigned phase):
        puActive(0),      // Start assumption: PU is off
        probOFFtoON(0),
        probONtoOFF(0),   // Those 2 are zeros because we don't need them in deterministic
        Tactive(Tactive_),
        offset(phase) {
        occupants.clear();
    }

    // Update function for Markov chain for PU
    void updateMarkov() {
        std::bernoulli_distribution trans(puActive ? probONtoOFF : probOFFtoON);
        // trans == a coin flip
        // set transition prob active->inactive or inactive->active based on current state
        bool Switch = trans(randEngine);
        if (Switch)  {
            puActive = !puActive;
            // determine if state should flip this timeslot or not
        }
        occupants.clear();
        // this resets the list of SUs using this band for the new time slot
    }

    // Update function for deterministic for PU
    void updateDeterministic(unsigned t) { // t represents the current time slot
        if (t < offset) puActive = 0;
        else {
            unsigned cycle = Tactive + TINACTIVE ;
            puActive = ( (t-offset) % cycle) < Tactive ;
            // Tactive is calculated and offset (random) is generated by executeSimulation() below
            // range of offset is 0-100
        }
        occupants.clear();
    }
};

class SecondaryUser {
public:
    unsigned int id;    // SU number
    std::vector<unsigned int> allocatedBands;
    std::vector<unsigned int> successfulBands;

    // secondary user constructor
    SecondaryUser(unsigned int userId) : id(userId) { // init list used for better performance
        allocatedBands.reserve(DEMAND) ;  // reserve prevents overallocation (exactly 5 slots)
        successfulBands.reserve(DEMAND) ;
    }

    // sense bands with miss detection if PU is active and false alarm if not
    std::vector<bool> senseBands(const std::vector<Band>& bands) {
        // passing by reference to minimize memory usage and runtime
        std::vector<bool> sensedEmpty(M); // Vector to store sensing results
        for (size_t m = 0; m < M; ++m) {
            bool actual = bands[m].puActive;
            if (actual) {
                // Fixed probability of miss detection (Pmd)
                bool missed = std::bernoulli_distribution(Pmd)(randEngine);
                sensedEmpty[m] = missed; // True if wrongly sensed as empty
            } else {
                // Fixed probability of false alarm (Pfa)
                bool falseAlarm = std::bernoulli_distribution(Pfa)(randEngine);
                sensedEmpty[m] = !falseAlarm; // True if correctly sensed as empty
            }
        }
        return sensedEmpty;
    }

    // allocate exactly DEMAND bands if enough empty bands are available
    std::vector<unsigned> allocateBands(const std::vector<bool>& sensedEmpty) {
        std::vector<unsigned> choices;
        // collect available bands:
        for (unsigned m = 0; m < M; ++m) {
            if (sensedEmpty[m]) choices.push_back(m);
        }
        std::shuffle(begin(choices), end(choices), randEngine);
        // Always take DEMAND bands unless fewer than DEMAND are available
        unsigned actualDemand = std::min(DEMAND, static_cast<unsigned>(choices.size()));
        allocatedBands = std::vector<unsigned>(choices.begin(), choices.begin() + actualDemand);
        return allocatedBands;
    }

    // clear bands for new time slot
    void resetForTimeSlot() {
        allocatedBands.clear();
        successfulBands.clear();
    }

    // count of successful bands (between 0-5)
    unsigned getSuccessfulBandCount() const {
        return successfulBands.size();
    }
};

// cooperative sensing using majority rule
std::vector<bool> majorityVote(const std::vector<std::vector<bool>>& allSensing) {
    std::vector<bool> result(M, false);
    for (size_t m = 0; m < M; ++m) {
        int votes = 0;
        for (size_t i = 0; i < allSensing.size(); ++i) {
            const auto& sensing = allSensing[i];
            if (sensing[m]) votes++;
        }
        result[m] = (votes > N/2);
    }
    return result;
}

void executeSimulation(bool markovMode, bool majoritySensing, double puProb, const std::string& filename) {
    std::vector<Band> bands;
    std::vector<SecondaryUser> users;

    // Initialize users with IDs
    for (unsigned n = 0; n < N; ++n) { // creating 10 SU objects with IDs 0-9
        users.emplace_back(n);
    }

    // Create frequency bands (markov or deterministic)
    if (markovMode) {
        // Create 100 bands, each initialized with puProb
        for (unsigned m = 0; m < M; ++m) {
            bands.emplace_back(puProb);
        }
    } else {
        unsigned Tactive = static_cast<unsigned>((puProb*TINACTIVE)/(1-puProb));
        std::uniform_int_distribution<unsigned> phaseDist(0, TINACTIVE);
        for (unsigned m = 0; m < M; ++m) {
            bands.emplace_back(Tactive, phaseDist(randEngine));
        }
    }

    // Track band 27 and SU7 specifically
    std::string trackingFilename = filename.substr(0, filename.find_last_of('.')) + "_band27_su7_tracking.csv" ;
    std::ofstream trackingFile(trackingFilename);
    trackingFile << "Slot,Band27_Throughput,Band27_Utilization,Band27_Interference," ;
    trackingFile << "SU7_SuccessfulTrans,SU7_Collisions,SU7_FalseAlarms,SU7_Misdetections\n" ;

    // per-time-slot metrics
    std::vector<unsigned> throughputPerSlot(SLOTS, 0);
    std::vector<unsigned> utilizationPerSlot(SLOTS, 0);
    std::vector<unsigned> collisionsPerSlot(SLOTS, 0);
    std::vector<unsigned> interferencePerSlot(SLOTS, 0);
    std::vector<unsigned> falseAlarmsPerSlot(SLOTS, 0) ;
    std::vector<unsigned> misdetectionsPerSlot(SLOTS, 0);
    std::vector<unsigned> successfulTxPerSlot(SLOTS, 0) ;
    std::vector<unsigned> totalFaAfterMajorityPerSlot(SLOTS, 0);
    std::vector<unsigned> totalMdAfterMajorityPerSlot(SLOTS, 0);

    // Per-band metrics
    std::vector<std::vector<unsigned>> throughputPerBand(M, std::vector<unsigned>(SLOTS, 0));
    std::vector<std::vector<unsigned>> utilizationPerBand(M, std::vector<unsigned>(SLOTS, 0));
    std::vector<std::vector<unsigned>> interferencePerBand(M, std::vector<unsigned>(SLOTS, 0));

    // Per-SU metrics
    std::vector<std::vector<unsigned>> suSuccessfulTx(N, std::vector<unsigned>(SLOTS, 0));
    std::vector<std::vector<unsigned>> suCollisions(N, std::vector<unsigned>(SLOTS, 0));
    std::vector<std::vector<unsigned>> suFalseAlarms(N, std::vector<unsigned>(SLOTS, 0));
    std::vector<std::vector<unsigned>> suMisdetections(N, std::vector<unsigned>(SLOTS, 0));
    std::vector<std::vector<unsigned>> suTotalFaAfterMajority(N, std::vector<unsigned>(SLOTS, 0));
    std::vector<std::vector<unsigned>> suTotalMdAfterMajority(N, std::vector<unsigned>(SLOTS, 0));

    // main loop
    for (unsigned t = 0; t < SLOTS; ++t){
        // Reset SU data for new time slot
        for (auto& user : users) {
            user.resetForTimeSlot();
        }
        // Update band states
        for (auto& band : bands) {
            if (markovMode) band.updateMarkov();
            else band.updateDeterministic(t);
        }

        // Sensing phase - track false alarms and misdetections for each SU
        std::vector<std::vector<bool>> allSensing;
        for (auto& user : users) {
            allSensing.push_back(user.senseBands(bands));
        }

        // Count false alarms and misdetections from raw sensing, before majority voting
        for (size_t i = 0; i < users.size(); ++i)  {
            for (size_t m = 0; m < M; ++m) {
                if (!allSensing[i][m] && !bands[m].puActive) {
                    // False alarm: SU thinks band is occupied but it's not
                    falseAlarmsPerSlot[t]++;
                    suFalseAlarms[i][t]++;
                }
                if (allSensing[i][m] && bands[m].puActive) {
                    // Misdetection: SU thinks band is empty but PU is active
                    misdetectionsPerSlot[t]++;
                    suMisdetections[i][t]++;
                }
            }
        }

        // Apply either majority vote or local sensing for band allocation
        std::vector<bool> commonSensedEmpty;
        if (majoritySensing) {
            commonSensedEmpty = majorityVote(allSensing);
            // Track false alarms and misdetections after majority voting
            for (size_t m = 0; m < M; ++m) {
                if (!commonSensedEmpty[m] && !bands[m].puActive) {
                    totalFaAfterMajorityPerSlot[t]++;
                    for (size_t i = 0; i < N; ++i) {
                        suTotalFaAfterMajority[i][t]++;
                    }
                }
                if (commonSensedEmpty[m] && bands[m].puActive) {
                    totalMdAfterMajorityPerSlot[t]++;
                    for (size_t i = 0; i < N; ++i) {
                        suTotalMdAfterMajority[i][t]++;
                    }
                }
            }
            // shared between all SUs by the fusion center
            for (auto& user : users) {
                user.allocateBands(commonSensedEmpty);
            }
        } else {
            for (size_t i = 0; i < users.size(); ++i) {
                users[i].allocateBands(allSensing[i]);
                // every SU depends on its own info, no fusion center
            }
        }

        // Register band occupancy
        for (auto& band : bands) {
            band.occupants.clear();
        }
        for (size_t i = 0; i < users.size(); ++i) {
            for (auto bandIdx : users[i].allocatedBands) {
                bands[bandIdx].occupants.push_back(i);
            }
        }

        // Determine successful transmissions for each SU
        for (size_t i = 0; i < users.size(); ++i) {
            users[i].successfulBands.clear();
            for (auto bandIdx : users[i].allocatedBands) {
                if (bands[bandIdx].occupants.size() == 1 && !bands[bandIdx].puActive) {
                    // successful if only one SU acquired the band (no collision nor interference)
                    users[i].successfulBands.push_back(bandIdx);
                }
            }
            suSuccessfulTx[i][t] = users[i].getSuccessfulBandCount();
        }

        // Calculate metrics for this time slot
        unsigned throughput = 0;
        unsigned utilization = 0;
        unsigned collisions = 0;
        unsigned interferenceCount = 0;
        unsigned successfulTransmissions = 0;

        for (size_t m = 0; m < M; ++m) {
            // Throughput: band used by exactly one SU with no PU
            bool throughputBand = (bands[m].occupants.size() == 1 && !bands[m].puActive);
            if (throughputBand) {
                throughput++;
                throughputPerBand[m][t] = 1;
            }
            // Utilization: band used by at least one SU
            bool utilizationBand = !bands[m].occupants.empty();
            if (utilizationBand) {
                utilization++;
                utilizationPerBand[m][t] = 1;
            }
            // Collisions: multiple SUs trying to use the same band
            if (bands[m].occupants.size() > 1 || (bands[m].puActive && bands[m].occupants.size() > 0)) {
                collisions += bands[m].occupants.size();
                for (auto userIdx : bands[m].occupants) {
                    suCollisions[userIdx][t]++;
                }
            }
            // Interference: SUs transmitting when PU is active
            bool interferenceBand = (!bands[m].occupants.empty() && bands[m].puActive);
            if (interferenceBand) {
                interferenceCount++;
                interferencePerBand[m][t] = 1;
            }
        }

        // Sum all successful transmissions across all SUs
        successfulTransmissions = 0;
        for (const auto& suData : suSuccessfulTx) {
            successfulTransmissions += suData[t];
        }
        throughputPerSlot[t] = throughput;
        utilizationPerSlot[t] = utilization;
        collisionsPerSlot[t] = collisions;
        interferencePerSlot[t] = interferenceCount;
        successfulTxPerSlot[t] = successfulTransmissions;

        // Write data to tracking file for band 27 and SU7
        trackingFile << t << ","
                     << throughputPerBand[27][t] << ","
                     << utilizationPerBand[27][t] << ","
                     << interferencePerBand[27][t] << ","
                     << suSuccessfulTx[7][t] << ","
                     << suCollisions[7][t] << ","
                     << suFalseAlarms[7][t] << ","
                     << suMisdetections[7][t] << "\n";
    }

    // Per-band averages
    std::string bandFilename = filename.substr(0, filename.find_last_of('.')) + "_band_averages.csv";
    std::ofstream bandFile(bandFilename);
    bandFile << "Band,AvgThroughput,AvgUtilization,AvgInterference\n";
    for (size_t m = 0; m < M; ++m) {
        double avgThroughput = std::accumulate(throughputPerBand[m].begin(), throughputPerBand[m].end(), 0.0) / SLOTS;
        double avgUtilization = std::accumulate(utilizationPerBand[m].begin(), utilizationPerBand[m].end(), 0.0) / SLOTS;
        double avgInterference = std::accumulate(interferencePerBand[m].begin(), interferencePerBand[m].end(), 0.0) / SLOTS;
        bandFile << m << "," << avgThroughput << "," << avgUtilization << "," << avgInterference << "\n";
    }

    // Per-SU averages
    std::string suFilename = filename.substr(0, filename.find_last_of('.')) + "_su_averages.csv";
    std::ofstream suFile(suFilename);
    suFile << "SU_ID,AvgSuccessfulBands,AvgCollisions,AvgFalseAlarms,AvgMisdetections,AvgTotalFaAfterMajority,AvgTotalMdAfterMajority\n";
    for (size_t i = 0; i < N; ++i) {
        double avgSuBands = std::accumulate(suSuccessfulTx[i].begin(), suSuccessfulTx[i].end(), 0.0) / SLOTS;
        double avgCollisions = std::accumulate(suCollisions[i].begin(), suCollisions[i].end(), 0.0) / SLOTS;
        double avgFalseAlarms = std::accumulate(suFalseAlarms[i].begin(), suFalseAlarms[i].end(), 0.0) / SLOTS;
        double avgMisdetections = std::accumulate(suMisdetections[i].begin(), suMisdetections[i].end(), 0.0) / SLOTS;
        double avgTotalFaAfterMajority = std::accumulate(suTotalFaAfterMajority[i].begin(), suTotalFaAfterMajority[i].end(), 0.0) / SLOTS;
        double avgTotalMdAfterMajority = std::accumulate(suTotalMdAfterMajority[i].begin(), suTotalMdAfterMajority[i].end(), 0.0) / SLOTS;
        suFile << i << "," << avgSuBands << "," << avgCollisions << "," << avgFalseAlarms << "," << avgMisdetections
               << "," << avgTotalFaAfterMajority << "," << avgTotalMdAfterMajority << "\n";
    }

    // Track SU successful bands across time slots
    std::string suBandsFilename = filename.substr(0, filename.find_last_of('.')) + "_su_bands_per_slot.csv";
    std::ofstream suBandsFile(suBandsFilename);
    suBandsFile << "TimeSlot";
    for (unsigned n = 0; n < N; ++n) {
        suBandsFile << ",SU" << n;
    }
    suBandsFile << "\n";
    for (unsigned t = 0; t < SLOTS; ++t) {
        suBandsFile << t;
        for (unsigned n = 0; n < N; ++n) {
            suBandsFile << "," << suSuccessfulTx[n][t];
        }
        suBandsFile << "\n";
    }

    // Average per-time-slot metrics
    std::string avgPerTimeSlotFilename = filename.substr(0, filename.find_last_of('.')) + "_avg_per_time_slot.csv";
    std::ofstream avgPerTimeSlotFile(avgPerTimeSlotFilename) ;
    avgPerTimeSlotFile << "TimeSlot,AvgThroughput,AvgUtilization,AvgInterference,";
    avgPerTimeSlotFile << "AvgSuccessfulTrans,AvgCollisions,AvgFalseAlarms,AvgMisdetections,";
    avgPerTimeSlotFile << "AvgTotalFaAfterMajority,AvgTotalMdAfterMajority\n";
    for (unsigned t = 0; t < SLOTS; ++t) {
        double avgThroughput = static_cast<double>(throughputPerSlot[t]) / M;
        double avgUtilization = static_cast<double>(utilizationPerSlot[t]) / M;
        double avgInterference = static_cast<double>(interferencePerSlot[t]) / M;
        double avgSuccessfulTrans = static_cast<double>(successfulTxPerSlot[t]) / N;
        double avgCollisions = static_cast<double>(collisionsPerSlot[t]) / N;
        double avgFalseAlarms = static_cast<double>(falseAlarmsPerSlot[t]) / N;
        double avgMisdetections = static_cast<double>(misdetectionsPerSlot[t]) / N;
        double avgTotalFaAfterMajority = static_cast<double>(totalFaAfterMajorityPerSlot[t]) / M;
        double avgTotalMdAfterMajority = static_cast<double>(totalMdAfterMajorityPerSlot[t]) / M;
        avgPerTimeSlotFile << t << ","
                           << avgThroughput << ","
                           << avgUtilization << ","
                           << avgInterference << ","
                           << avgSuccessfulTrans << ","
                           << avgCollisions << ","
                           << avgFalseAlarms << ","
                           << avgMisdetections << ","
                           << avgTotalFaAfterMajority << ","
                           << avgTotalMdAfterMajority << "\n";
    }
}

int main()
{
    for (double prob : {0.2, 0.4, 0.5, 0.6}) {
        executeSimulation(true, false, prob, "markov_local_probability" + std::to_string(int(prob*100)) + ".csv");
        executeSimulation(true, true, prob, "markov_cooperative_probability" + std::to_string(int(prob*100)) + ".csv");
        executeSimulation(false, false, prob, "deterministic_local_probability" + std::to_string(int(prob*100)) + ".csv");
        executeSimulation(false, true, prob, "deterministic_cooperative_probability" + std::to_string(int(prob*100)) + ".csv");
    }
    std::cout << "Simulations completed successfully.\n";
    return 0;
}
